name: piranha-installer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda
  - medaka=1.11.3
  - piranha-polio
  - python
  - snakemake
  - pyinstaller
  - tzdata=2025a # 2025c and latest 2025b breaks pyinstaller!